name: expenseiq
description: Personal Expense & Income Manager
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  dio: ^5.4.3

  # Local Storage & Auth
  flutter_secure_storage: ^9.0.0

  # File Picking (XLS Upload)
  file_picker: ^8.0.3

  # Charts
  fl_chart: ^0.67.0

  # UI
  cupertino_icons: ^1.0.6
  intl: ^0.19.0

  # New features
  share_plus: ^7.2.2
  url_launcher: ^6.2.5
  flutter_contacts: ^1.1.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  mockito: ^5.4.4
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
