# Generated by Django 5.0.4 on 2026-05-29 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_app',
            field=models.CharField(blank=True, help_text='Specific app used (e.g., GPay)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('neft', 'NEFT/IMPS/RTGS'), ('card_debit', 'Debit Card'), ('card_credit', 'Credit Card'), ('wallet', 'Wallet'), ('cheque', 'Cheque'), ('other', 'Other')], help_text='Payment method used', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shared_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid on behalf of others', max_digits=12),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DebtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('lend', 'Lend'), ('borrow', 'Borrow')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('is_settled', models.BooleanField(default=False)),
                ('settled_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_records', to='expenses.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
